
// TMSCreateCriteria
export const TMSCCR_GET_TABLE_COLUMN = "TMSCCR_GET_TABLE_COLUMN";
export const TMSCCR_GET_COLUMN = "TMSCCR_GET_COLUMN";
export const TMSCCR_GET_TABLE = "TMSCCR_GET_TABLE";
export const TMSCCR_SET_CRITERIA = "TMSCCR_SET_CRITERIA";
export const TMSCCR_SET_SELECT_TABLE = "TMSCCR_SET_SELECT_TABLE";
export const TMSCCR_SET_RUN_TIME = "TMSCCR_SET_RUN_TIME";
export const TMSCCR_RESET = "TMSCCR_RESET";


// TMSScheduledEmail
export const TMSSER_SET_WEEKLY_OPTION = "TMSSER_SET_WEEKLY_OPTION";
export const TMSSER_SET_QUARTER_OPTION = "TMSSER_SET_QUARTER_OPTION";
export const TMSSER_SET_MONTHLY_OPTION = "TMSSER_SET_MONTHLY_OPTION";
export const TMSSER_SET_SELECTED_SCHEDULE = "TMSSER_SET_SELECTED_SCHEDULE";
export const TMSSER_RESET = "TMSSER_RESET";

// TMSCreateTaskGroup
export const TMSCTGR_SET_MODAL_STATUS = "TMSESR_SET_MODAL_STATUS";
export const TMSCTGR_SET_TASKGROUP_NAME = "TMSCTGR_SET_TASKGROUP_NAME";
export const TMSCTGR_GET_TASKGROUP_INFO = "TMSCTGR_GET_TASKGROUP_INFO";
export const TMSCTGR_SET_TASKGROUP_ID = "TMSCTGR_SET_TASKGROUP_ID";
export const TMSCTGR_SET_DATA_ENTRY = "TMSCTGR_SET_DATA_ENTRY";
export const TMSCTGR_RESET = "TMSCTGR_RESET";

// TMSEmailSearch
export const TMSESR_SET_OPEN_EMAIL_SEARCH = "TMSESR_SET_OPEN_EMAIL_SEARCH";
export const TMSESR_GET_LDAP_RESULT = "TMSESR_GET_LDAP_RESULT";
export const TMSESR_SET_SEARCH_VALUE = "TMSESR_SET_SEARCH_VALUE";
export const TMSESR_SET_DISABLE_SEARCH_BUTTON = "TMSESR_SET_DISABLE_SEARCH_BUTTON";
export const TMSESR_ADD_UMS_EMAIL = "TMSESR_ADD_UMS_EMAIL";
export const TMSESR_ADD_UMS_EMAIL_OPTIONS = "TMSESR_ADD_UMS_EMAIL_OPTIONS";
export const TMSESR_SET_SELECTED_VALUE = "TMSESR_SET_SELECTED_VALUE";
export const TMSESR_SET_MODAL_VALUES = "TMSESR_SET_MODAL_VALUES";
export const TMSESR_SET_MULTI_VALUE = "TMSESR_SET_MULTI_VALUE";
export const TMSESR_RESET = "TMSESR_RESET"; 
export const TMSESR_GET_UMS_EMAIL = "TMSESR_GET_UMS_EMAIL"; 

// TMSCreateApplication 
export const TMSCAR_SET_MODAL_STATUS = "TMSCAR_MODAL_STATUS";
export const TMSCAR_SET_INVALID_APP_INPUT = "TMSCAR_SET_INVALID_APP_INPUT";
export const TMSCAR_SET_DISABLE_CREATE = "TMSCAR_SET_DISABLE_CREATE";
export const TMSCAR_GET_APPLICATION_LIST = "TMSCAR_GET_APPLICATION_LIST";
export const TMSCAR_SET_APPLICATION_OBJ = "TMSCAR_SET_APPLICATION_OBJ";
export const TMSCAR_SET_APP_CUR_LIST = "TMSCAR_SET_APP_CUR_LIST";
export const TMSCAR_SET_GROUP_NAME_CUR_LIST = "TMSCAR_SET_GROUP_NAME_CUR_LIST";

// TMSCreateTask 
export const TMSCT_SET_APPLICATION_NAME = "TMSCT_APPLICATION_NAME";
export const TMSCT_SET_TASK_LIST = "TMSCT_TASK_LIST";
export const TMSCT_SET_DISABLE_TASK_GROUP = "TMSCT_SET_DISABLE_TASK_GROUP";
export const TMSCT_SET_TASK_GROUP = "TMSCT_SET_TASK_GROUP";
export const TMSCT_SET_DISABLE_TASK_NAME = "TMSCT_SET_DISABLE_TASK_NAME"; 
export const TMSCT_SET_TASK_NAME = "TMSCT_SET_TASK_NAME"; 
export const TMSCT_SET_DISABLE_TASK_DESC = "TMSCT_SET_DISABLE_TASK_DESC";  
export const TMSCT_SET_TASK_DESC = "TMSCT_SET_TASK_DESC"; 
export const TMSCT_SET_DISABLE_ADD_BUTTON = "TMSCT_SET_DISABLE_ADD_BUTTON"; 
export const TMSCT_SET_DISABLE_IS_MANDATORY = "TMSCT_SET_DISABLE_IS_MANDATORY";  
export const TMSCT_SET_TASKGROUP_LIST = "TMSCT_SET_TASKGROUP_LIST";  
export const TMSCT_SET_TASK_LIST_DELETED = "TMSCT_SET_TASK_LIST_DELETED"; 

// TMSTasksDataTable
export const TMSTDTR_SET_SELECTED_ROW = "TMSTDTR_SET_SELECTED_ROW";  
export const TMSTDTR_SET_EDIT_DATE = "TMSTDTR_SET_EDIT_DATE";  
export const TMSTDTR_GET_TASK_INFO = "TMSTDTR_GET_TASK_INFO";
export const TMSTDTR_UPDATE_TASK_ROW = "TMSTDTR_UPDATE_TASK_ROW";
export const TMSTDTR_SELECTED_TASK_ROW = "TMSTDTR_SELECTED_TASK_ROW";
export const TMSTDTR_SET_TASK_INFO = "TMSTDTR_SET_TASK_INFO";
export const TMSTDTR_SET_PREVIOUS_ID = "TMSTDTR_SET_PREVIOUS_ID";
export const TMSTDTR_SET_MERGE_DATA = "TMSTDTR_SET_MERGE_DATA";
export const TMSTDTR_SET_STATUS_SELECTION = "TMSTDTR_SET_STATUS_SELECTION";

// TMSMain
export const TMSMR_OPEN_TOAST = "TMSMR_OPEN_TOAST";
export const TMSMR_SET_OBJECT = "TMSMR_SET_OBJECT";
export const TMSMR_OPEN_LOADING = "TMSMR_OPEN_LOADING";
export const TMSMR_REFRESH = "TMSMR_REFRESH";
export const TMSMR_RETURN_HOME = "TMSMR_RETURN_HOME";
export const TMSMR_USER_INFO = "TMSMR_USER_INFO";
export const TMSMR_GET_STATUS_DEFS = "TMSMR_GET_STATUS_DEFS";
export const TMSMR_GET_GROUP_NAME = "TMSMR_GET_GROUP_NAME";
export const TMSMR_GET_CRITERIA_TABLES_COLUMNS = "TMSMR_GET_CRITERIA_TABLES_COLUMNS";

// TMSActionDataTable
export const TMSADTR_GET_ACTION_INFO = "TMSADTR_GET_ACTION_INFO";
export const TMSADTR_FILTER_ACTION_INFO = "TMSADTR_FILTER_ACTION_INFO";
export const TMSADTR_SET_DIALOG_DELETE = "TMSADTR_SET_DIALOG_DELETE";
export const TMSADTR_SET_SHOW_FILE_LIST = "TMSADTR_SET_SHOW_FILE_LIST";

// TMSAddAction
export const TMSAAR_SET_UPLOAD_ARRAY = "TMSAAR_SET_UPLOAD_ARRAY"; 
export const TMSAAR_SET_STATUS_SELECTION = "TMSAAR_SET_STATUS_SELECTION"; 
export const TMSAAR_SET_STATUS_DATA = "TMSAAR_SET_STATUS_DATA"; 
export const TMSAAR_SET_ACTION_DATA = "TMSAAR_SET_ACTION_DATA"; 
export const TMSAAR_SET_SHOW_CREATE_STATUS = "TMSAAR_SET_SHOW_CREATE_STATUS"; 

// TMSAddTask
export const TMSATR_SET_TASK_INFO = "TMSATR_SET_TASK_INFO"; 
export const TMSATR_SET_APPLICATION_INFO = "TMSATR_SET_APPLICATION_INFO"; 
export const TMSATR_SET_TASK_GROUP_INFO = "TMSATR_SET_TASK_GROUP_INFO"; 
export const TMSATR_SET_TASKS = "TMSATR_SET_TASKS"; 

// FOR Action module PPI 
export const TMSPPIAAR_SET_SHOW_MODAL = "TMSPPIAAR_SET_TOGGLE"; 
export const TMSPPIAAR_SET_SHORTAGE_INFO = "TMSPPIAAR_SET_SHORTAGE_INFO"; 


